### ISSUE TITLE
Enhancing style of scrollBar

### ISSUE THREAD

**Issue by Akshanshkaushal** [PranabKumarSahoo/sql-dev-tools#1]
While the site boasts an interactive and captivating interface, I believe introducing a more refined navbar would elevate its elegance further. I am eager to enhance this aspect and contribute to a seamless and visually appealing user experience.

**Comment by Dhananjayshukla1** [comment]
@PranabKumarSahoo I want to contribute to this project, could please assign this to me?

**Comment by younikarn** [comment]
Can I take this issue? Please assign it to me under SWOC'24

**Comment by PranabKumarSahoo** [comment]
Hello ⭐
Thank you all for expressing your interest in enhancing the scrollbar style! It's great to see such enthusiasm to contribute.

@Akshanshkaushal This issue is now assigned to you since you opened it. Please feel free to start working on enhancing the navbar style. If you encounter any challenges or have questions, don't hesitate to ask for assistance.

@Dhananjayshukla1 & @younikarn, While Akshanshkaushal takes the lead on this issue, I encourage collaboration. If Akshanshkaushal is open to it, feel free to coordinate and work together to enhance the scrollbar style seamlessly. (You can create your own issues. right!!)

@Akshanshkaushal If, for any reason, you are unable to work on this or need more time, please let us know. @Dhananjayshukla1 and @younikarn have also expressed interest, and we can reassign the issue accordingly.

**Happy Contribution!✌️**

**Comment by Akshanshkaushal** [comment]
@PranabKumarSahoo Thanks for assigning ,I'm working on the issue . If @younikarn and @Dhananjayshukla1 you want to collaborate can connect on discord. If you are interested in working together or have any suggestions for improvements, please feel free to connect with me on Discord.
![Screenshot (172)](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/113452367/8c72fbad-1c58-4503-8d74-19c31cf2cb87)

**Comment by PranabKumarSahoo** [comment]
**Join [Discord Channel](https://discord.com/channels/1118073956960841815/1191064181986824242) for discussion/doubts/questions. ✌️**
