### ISSUE TITLE
Enhancing the submit button

### ISSUE THREAD

**Issue by KhushiAgarwal-01** [PranabKumarSahoo/sql-dev-tools#10]
Add some dynamic styling to the submit button for better user interaction

**Comment by KhushiAgarwal-01** [comment]
I can work on this issue

**Comment by PranabKumarSahoo** [comment]
Hello @KhushiAgarwal-01,
Thank you for creating an issue on this! ⭐ 

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by KhushiAgarwal-01** [comment]
Uploading sql-dev-tools.mp4…

**Comment by KhushiAgarwal-01** [comment]
https://github.com/PranabKumarSahoo/sql-dev-tools/assets/141832113/979d6c45-9ba4-4ddf-83ba-a2a1d0ff47e3

**Comment by PranabKumarSahoo** [comment]
Looks nice @KhushiAgarwal-01, ⭐

Have you added this dynamic UI button for all sections!?
Because in this project, latest new 2 tools/sections are added. Have you added in these also!?

If Yes, can you show me the changes through video for all sections!?
Otherwise, you can raise the PR.

**Thanks for the Contribution!** 

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**
