### ISSUE TITLE
creating guide button for all section

### ISSUE THREAD

**Issue by sagarbee** [PranabKumarSahoo/sql-dev-tools#16]
creating guide button for all section which will show instruction with example, which will help users to understand how to use section properly. guide button will work alternatly like when press it will show details in outputbox and when it press again it will clear outputbox.

will create it for all sections:
1.Drop Constraint
2.Count of Rows
3.Custom Statement
4.Nth Highest

**Comment by PranabKumarSahoo** [comment]
Hello @sagarbee,
Thank you for creating an issue! ⭐ 

Yah! That's a cool idea for users.
So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number in your PR in the following format: Resolve issue #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by sagarbee** [comment]
here's demo guide button created for nth highest

https://github.com/PranabKumarSahoo/sql-dev-tools/assets/65588552/90ae3315-0fa6-47e8-b219-b6d24fe78cea

**Comment by PranabKumarSahoo** [comment]
Very good job @sagarbee! ⭐

I appreciate your work on adding the guide button to the tool, making it more user-friendly. After testing the recent enhancement, I was thinking it might be even more effective if the guide instructions were displayed in a pop-up modal box rather than the output textbox. This would provide a cleaner and more focused user experience.

What do you think?

Let me know your thoughts on this suggestion!!

**Thanks again for your contributions!**

---
**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
Hello @sagarbee,

Please keep me update your work progress on this issue. Thank you!✌️

**Comment by ayann07** [comment]
Can I work on this?

**Comment by PranabKumarSahoo** [comment]
Hello @ayann07,

Absolutely, you can work on this! Thank you for stepping up.

@sagarbee, I appreciate your efforts so far on this issue. Since @ayann07 is willing to take over, I'll assign the task to him.

So, @ayann07, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 

Make sure to follow our [Contribution Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/CONTRIBUTING.md) & [PR Guidelines](https://github.com/PranabKumarSahoo/sql-dev-tools/blob/main/pull_request_template.md).

**Thanks for the contributions!**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel].

**#Good luck! ✌️**

**Comment by PranabKumarSahoo** [comment]
This issue is solved. Now I'm closing this.

**Thanks for the contributions!**
