### ISSUE TITLE
Enhancing all user Experience on Buttons 

### ISSUE THREAD

**Issue by RonitBaranwal** [PranabKumarSahoo/sql-dev-tools#17]
A very well thought of project , but what I have seen is that the btns do not provide the good user experience ,so would like to add some transition effects on it if its okay for you..

**Comment by PranabKumarSahoo** [comment]
Hello @RonitBaranwal,
Thanks for creating an issue on this! ⭐

I'm aware that this issue is quite familiar with #10 issue which is related to the Buttons Design. 
So I suggest that you can collaborate with the contributor of #10 issue.

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**

**Comment by RonitBaranwal** [comment]
Okay its fine. if someone else is already working into it then you can close this issue.

**Comment by PranabKumarSahoo** [comment]
Thanks for your understanding @RonitBaranwal!

Feel free to create another issues.

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px). 

**#Good luck! ✌️**
