### ISSUE TITLE
[Feat] : Enhancing the UI of input all the input fields

### ISSUE THREAD

**Issue by SulagnaKundu** [PranabKumarSahoo/sql-dev-tools#23]
## Describe the feature
I want to make the input fields look similar all throughout the website.

## Screenshots
![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/103977344/bbd69051-b3f0-48af-a294-351e9f03a754)

![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/103977344/858b634c-5809-498b-a61a-1e3bc11bec2c)

In the above two pictures, the border of the input fields are not same as marked. We can make them look similar , in order to enhance the UI feature of the website.

**Comment by PranabKumarSahoo** [comment]
Hello @SulagnaKundu,
Thank you for creating an issue! ⭐ 

So, I'm officially assigning this task to you under **SWOC**. So feel free to start working on it. 
Please keep me updated on your progress through images/videos in the comment section before raising the PR.

**PS: Always mention the issue number, When you raise your PR in the following format: Resolve issue: #<issue_number>**

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel]. 

**#Good luck! ✌️**

**Comment by SulagnaKundu** [comment]
Shall I close this issue and work on a different one as this issue has been marked invalid?

**Comment by PranabKumarSahoo** [comment]
@SulagnaKundu, 
Yes, there's no need to design the input border of Custom Statement section.

Actually there's a reason!
- You can see the input border of "**Count of Rows**", there's default Red border in the input, because that input field is mandatory.

- But for the "**Custom Statement**" input field, there's no need, because the input fields are not mandatory as there's the prefix and suffix statements only. We can add prefix as well as suffix statement. But not mandatory.

Hope you got my point! ✌️

Anyways, As this is not a valid issue. So I closed this issue.
You can create or work on another issues. 

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) [Find **#sql-dev-tools** channel]. 

**#Good luck! ✌️**

**Comment by SulagnaKundu** [comment]
Oh Okay! I got the reason. 
I will look for other issues to contribute.
