### ISSUE TITLE
Add arrow up button

### ISSUE THREAD

**Issue by mansi1309** [PranabKumarSahoo/sql-dev-tools#44]
I would like to add arrow up button in page so that we can directly go on top of page. Please assign this to me .I would like to add my contribution in this project.
![image](https://github.com/PranabKumarSahoo/sql-dev-tools/assets/133951716/bbc02056-7a93-4bc7-b8c5-d4830e05791d)

**Comment by PranabKumarSahoo** [comment]
Hello @mansi1309,
Thanks for creating an issue on this! ⭐

I'm aware that this issue is quite familiar with #12 issue which is related to **Scroll Up** Button for the same. And that issue is already been solved by another contributor. If you try to clone the recent repo, you can found out.

So, please feel free to create another issues/contribute to more, If you found any.
And try to reply in this comment, so that I can close this issue.

Thanks again!

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) **[Find #sql-dev-tools channel]**. 

**#Good luck! ✌️**
