### ISSUE TITLE
ADDING HOVER ON BUTTON

### ISSUE THREAD

**Issue by mansi1309** [PranabKumarSahoo/sql-dev-tools#46]
I would like to add hover on clicking submit button so that it looks good. Please assign this to me.

**Comment by PranabKumarSahoo** [comment]
Hello @mansi1309,
Thanks for creating an issue on this! ⭐

I'm aware that this issue is quite familiar with #10 issue which is related to **Buttons Design** for the same. And also this issue is already been implemented by another contributor.

I would recommend, before you start creating any issues, first of all clone the recent repository version onto your local machine and running it on your localhost. This way, you can interact with the latest updates, analyze the current interface, and identify any additional features or improvements that may be needed & also don't forget to read the documentation for complete guidelines.

So, feel free to explore the recent changes. If you found any issues which could be solved by you, then create the issues. 
Hope you understand my points. Still, If you have any questions or need guidance, don't hesitate to ask.

## Happy contributing!

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) **[Find #sql-dev-tools channel]**. 

**#Good luck! ✌️**
