### ISSUE TITLE
Add scroll up and down arrow button

### ISSUE THREAD

**Issue by Ishita928** [PranabKumarSahoo/sql-dev-tools#50]
scroll up and down button needs to be added ,makes easy for users to move vertically on the website

**Comment by PranabKumarSahoo** [comment]
Hello @Ishita928,
Thanks for creating an issue on this! ⭐

I'm aware that this issue is quite familiar with #12 issue which is related to **Scroll Up** Button for the same. And that issue is already been solved by another contributor. If you try to clone recent version of the repo, you can found out.

So, please feel free to create another issues/contribute to more, If you found any.
And try to reply in this comment, so that I can close this issue.

Thanks again!

---
If you have any questions or need clarification, don't hesitate to ask in the comments or on [Discord](https://discord.gg/TSYH66px) **[Find #sql-dev-tools channel]**. 

**#Good luck! ✌️**

**Comment by Ishita928** [comment]
Thanks for your response, I will surely contribute if i find any other issue

**Comment by PranabKumarSahoo** [comment]
Thanks for your understanding. Now I'm going to close the issue.

Feel free to create more issues/contribute more.

---
#Good Luck!✌️
